#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libvorbis
Version  : 1.3.5
Release  : 1
URL      : http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.xz
Source0  : http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.xz
Summary  : Vorbis Library Development
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libvorbis-lib
Requires: libvorbis-doc
BuildRequires : pkgconfig(ogg)

%description
Ogg Vorbis is a fully open, non-proprietary, patent-and-royalty-free,
general-purpose compressed audio format for audio and music at fixed 
and variable bitrates from 16 to 128 kbps/channel.

%package dev
Summary: dev components for the libvorbis package.
Group: Development
Requires: libvorbis-lib
Provides: libvorbis-devel

%description dev
dev components for the libvorbis package.


%package doc
Summary: doc components for the libvorbis package.
Group: Documentation

%description doc
doc components for the libvorbis package.


%package lib
Summary: lib components for the libvorbis package.
Group: Libraries

%description lib
lib components for the libvorbis package.


%prep
%setup -q -n libvorbis-1.3.5

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make check || :

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/vorbis/codec.h
/usr/include/vorbis/vorbisenc.h
/usr/include/vorbis/vorbisfile.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc
/usr/share/aclocal/*.m4

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libvorbis/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
